function AE = AEfunc(dq1,dq2,dq4,l1,l2,q1,q2,q4)
%AEFUNC
%    AE = AEFUNC(DQ1,DQ2,DQ4,L1,L2,Q1,Q2,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    25-Apr-2022 11:56:57

AE = (dq4.*sin(q2)+dq1.*l1.*cos(q1)+dq2.*cos(q2).*(l2+q4)).^2;
