function out1 = Efunc(A_2,E2,I2,Rho2,dq1,dq2,dq3,dq4,dq5,g,l1,l2,m1,m3,q1,q2,q3,q4,q5)
%EFUNC
%    OUT1 = EFUNC(A_2,E2,I2,RHO2,DQ1,DQ2,DQ3,DQ4,DQ5,G,L1,L2,M1,M3,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    25-Apr-2022 11:56:56

t2 = cos(q2);
t3 = sin(q1);
t4 = sin(q2);
t5 = dq1.^2;
t6 = dq2.^2;
t7 = l1.^2;
t8 = l2.^2;
t9 = q3.^2;
t10 = q4.^2;
t11 = q5.^2;
t12 = 1.0./l2;
t13 = -q2;
t14 = q1+t13;
t15 = cos(t14);
t16 = sin(t14);
out1 = (m3.*(-dq4.*t2+dq1.*l1.*t3+dq2.*l2.*t4+dq2.*q4.*t4).^2)./2.0+(m1.*t5.*t7)./6.0+(g.*l1.*m1.*t3)./2.0+(A_2.*Rho2.*l2.*(t5.*t7.*2.1e+2+t6.*t8.*7.0e+1+t6.*t10.*7.0e+1+dq3.^2.*t8.*2.0+dq5.^2.*t8.*2.0+dq4.^2.*7.0e+1+dq2.*dq3.*t8.*1.4e+1-dq2.*dq5.*t8.*2.1e+1-dq3.*dq5.*t8.*3.0+l2.*q4.*t6.*1.4e+2+t6.*t8.*t9.*2.0+t6.*t8.*t11.*2.0+dq2.*dq3.*l2.*q4.*1.4e+1-dq2.*dq4.*l2.*q3.*1.4e+1+dq2.*dq4.*l2.*q5.*2.1e+1-dq2.*dq5.*l2.*q4.*2.1e+1-dq1.*dq4.*l1.*t16.*2.1e+2-q3.*q5.*t6.*t8.*3.0+dq1.*dq2.*l1.*l2.*t15.*2.1e+2+dq1.*dq3.*l1.*l2.*t15.*3.5e+1-dq1.*dq5.*l1.*l2.*t15.*3.5e+1+dq1.*dq2.*l1.*q4.*t15.*2.1e+2+dq1.*dq2.*l1.*l2.*q3.*t16.*3.5e+1-dq1.*dq2.*l1.*l2.*q5.*t16.*3.5e+1))./4.2e+2+(A_2.*E2.*t10.*t12)./2.0+E2.*I2.*t12.*(t9+t11+q3.*q5).*2.0+(A_2.*Rho2.*g.*l2.*(l1.*t3.*1.2e+1+l2.*t4.*6.0+q4.*t4.*6.0+l2.*q3.*t2-l2.*q5.*t2))./1.2e+1;
