function A1dot = A1dotfunc(dq1,dq2,l1,l2,q1,q2)
%A1DOTFUNC
%    A1DOT = A1DOTFUNC(DQ1,DQ2,L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Apr-2022 07:39:38

A1dot = [-dq1.*l1.*sin(q1);-dq2.*l2.*sin(q2)];
