function A1 = A1func(l1,l2,q1,q2)
%A1FUNC
%    A1 = A1FUNC(L1,L2,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Apr-2022 07:39:38

A1 = [l1.*cos(q1);l2.*cos(q2)];
