function out1 = Efunc(dq1,dq2,g,l1,l2,m1,m2,m3,q1,q2)
%EFUNC
%    OUT1 = EFUNC(DQ1,DQ2,G,L1,L2,M1,M2,M3,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Apr-2022 07:39:39

t2 = sin(q1);
t3 = sin(q2);
t4 = dq1.^2;
t5 = l1.^2;
out1 = (m2.*(t4.*t5.*3.0+dq2.^2.*l2.^2+dq1.*dq2.*l1.*l2.*cos(q1-q2).*3.0))./6.0+(m3.*(dq1.*l1.*t2+dq2.*l2.*t3).^2)./2.0+(g.*m2.*(l1.*t2.*2.0+l2.*t3))./2.0+(m1.*t4.*t5)./6.0+(g.*l1.*m1.*t2)./2.0;
