function M = Mfunc(l1,l2,m1,m2,m3,q1,q2)
%MFUNC
%    M = MFUNC(L1,L2,M1,M2,M3,Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Apr-2022 07:39:37

t2 = sin(q1);
t3 = sin(q2);
t4 = -q2;
t5 = q1+t4;
t7 = m3.*t2.*t3.*2.0;
t6 = cos(t5);
t8 = m2.*t6;
t9 = t7+t8;
t10 = (l1.*l2.*t9)./2.0;
M = reshape([(l1.^2.*(m1+m2.*3.0+m3.*t2.^2.*3.0))./3.0,t10,t10,(l2.^2.*(m2+m3.*t3.^2.*3.0))./3.0],[2,2]);
